import { Inter } from 'next/font/google'
import "./css/main.scss"

import Cabecalho from '@/components/Cabecalho/Cabecalho'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'JARVIS',
  description: 'Generated by Jarvis ',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        
        <Cabecalho/>
        {children}
        
        
        </body>
    </html>
  )
}
